### ISSUE TITLE
Question on LUIS and Entity, Intent setup

### ISSUE THREAD

**Issue by MK36EB** [IntelligentLabs/InBytes-BotFramework#1]
Hi there IntelligentLabs,

This is not an issue by any means, more like a couple of questions. I’m not sure if this is the right place to ask them but I would prefer to ask them here as opposed to on your YouTube Channel.

On account of your experience in working with the Microsoft Bot Framework, what is the minimum project setup required in order to bring in a LUIS file? I am more of a business analyst by trade and find it easier to work in the LUIS web interface. Can I get away with doing everything in LUIS and then associating it with a Bot Framework project?

My second question relates to my understanding of entities, intents and utterances. I am attempting to build a bot for Skype that answers regular questions for a Fab Lab I am busy with. I have looked at the FAQ’s for a dozen Fab Labs and listed them in a spreadsheet. I have setup entity parents, entity children, intents, utterances and phrase lists. Before I build anything (depending on the answer to Q1) I just wanted to pass it through someone who really had some experience in this area.

Fab Lab – www.fablabs.io

The typical questions are what machines do you have, what material do I need, can I book a machine, when are you open, what can I print with a 3D printer, what can I prototype, etc etc.

Thanks for taking the time to read this. My email is elliot@1point3creative.com, if it is ok with you to email you the spreadsheet to cast your eye over.

Thanks in advance,
Elliot

**Comment by IntelligentLabs** [comment]
Hi Elliot,

Hopefully I can help answer your questions here. The most difficult part to get right in your scenario will be the LUIS utterances, intents and entities as you will have to put the work into ensuring that the what the user is saying is reliably sent to the correct intent. This work could all be done from the LUIS web page and wont need visual studio.

For the bot, you should be able to keep the code pretty simple. All you should need based on what you have said is
-Small library that reads in your spreadsheet and creates a list or dictionary with the values in it. You would then have small methods to get the correct information based on the intent.
-For the bot you would need a single LUIS Dialog that had a method for each intent you have programmed in LUIS that just calls the library you created and returns the reply to your bot.
-Then in the bot MessagesController you would call your LUIS Dialog for any Activity.

If you need any help with the code for the bot, or would like to me to put something together for reading and searching the spreadsheet let me know and I will be happy to help. You can contact me and send your spreadsheet if you want me to look at that at dave.green@intelligentlabs.co.uk

Thanks,
Dave

**Comment by MK36EB** [comment]
Hi Dave,

It is very good and gracious of you to get back to me and much appreciated.

The response is very informative and much along the lines of what I was hoping for. I don’t want to take the easy way out and just ask you for help too soon, I may miss the opportunity to learn something. I’ll take the approach of continuing to build out the LUIS model over the next few days and then pass the spreadsheet and model over to you.

Perhaps you could cast your eye over it and highlight where I’ve gone right/wrong. I won’t be offended if I have got it all wrong and have to do it all again, I’d like to be able to join all the dots up in my mind and conversations like these are very helpful.

If the entities, intents, and utterances are as they should be I can then move to programming the Bot.

Thanks again Dave, I’ll probably be in touch again on or around the weekend.

All good wishes,
Elliot

**Comment by IntelligentLabs** [comment]
We are working on this outside of GitHub now as its about bots in general and not this specific code.
