### ISSUE TITLE
service that sends news

### ISSUE THREAD

**Issue by andrecordeiro** [IntelligentLabs/InBytes-BotFramework#2]
I have a published bot microsoft, running on the telegram and on facebook, right. How do I create a service that sends news to these bots from time to time? I do not know how to automatically send messages to my bots microsoft. In the telegram I can send using a script in php. Can you help me? Thank you very much.﻿

**Comment by IntelligentLabs** [comment]
Hi I have responded to your comment on the YouTube video for this.
